import type { AppState } from '../types';
import { getDefaultWeights } from '../core/tpms-functions';
import { downloadBlob } from './download';

/**
 * 导出 Python (PyVista/NumPy) 重建脚本
 */
export function exportPythonScript(state: AppState, filename: string): void {
  const hybridWeights = state.hybrid.enabled ? getDefaultWeights(state.hybrid.typeB) : null;
  const script = `# TPMS 参数化重建脚本 (PyVista)
# Generated by TPMS Explorer
# 注意：本平台使用 Surface Nets 算法，而脚本使用 Marching Cubes，结果可能略有差异。
# 运行: pip install numpy pyvista

import numpy as np
import pyvista as pv

# 参数配置
tpms_type = '${state.type}'
porosity = ${state.porosity}
cell_size = ${state.cellSize}
thickness = ${state.thickness}
weights = [${state.weights.join(', ')}]
structure_mode = '${state.structureMode}'
container = '${state.containerShape}'
gradient_dir = '${state.gradientDir}'

# 分辨率
R = 19 + cell_size * 14
N = R + 1

# 生成坐标网格
x = np.linspace(-np.pi, np.pi, N)
y = np.linspace(-np.pi, np.pi, N)
z = np.linspace(-np.pi, np.pi, N)
X, Y, Z = np.meshgrid(x, y, z, indexing='ij')

# 隐函数场
def tpms_field(X, Y, Z, w, tpms_type_override=None):
    t = tpms_type_override if tpms_type_override is not None else tpms_type
    if t == 'gyroid':
        return w[0]*np.sin(X)*np.cos(Y) + w[1]*np.sin(Y)*np.cos(Z) + w[2]*np.sin(Z)*np.cos(X)
    elif t == 'diamond':
        return (w[0]*np.cos(X)*np.cos(Y)*np.cos(Z) -
                w[1]*np.sin(X)*np.sin(Y)*np.sin(Z) +
                w[2]*np.cos(X)*np.sin(Y)*np.sin(Z) +
                w[3]*np.sin(X)*np.cos(Y)*np.sin(Z))
    elif t == 'schwarz':
        return w[0]*np.cos(X) + w[1]*np.cos(Y) + w[2]*np.cos(Z)
    elif t == 'neovius':
        return 3*w[0]*(np.cos(X) + np.cos(Y) + np.cos(Z)) + 4*w[1]*np.cos(X)*np.cos(Y)*np.cos(Z)
    elif t == 'iwp':
        return (2*w[0]*(np.cos(X)*np.cos(Y) + np.cos(Y)*np.cos(Z) + np.cos(Z)*np.cos(X))
                - w[1]*(np.cos(2*X) + np.cos(2*Y) + np.cos(2*Z)))
    elif t == 'frd':
        return (4*w[0]*np.cos(X)*np.cos(Y)*np.cos(Z)
                - w[1]*(np.cos(2*X)*np.cos(2*Y) + np.cos(2*Y)*np.cos(2*Z) + np.cos(2*Z)*np.cos(2*X)))
    elif t == 'lidinoid':
        return (0.5 * w[0] * (2*np.sin(X)*np.cos(X)*np.cos(Y)*np.sin(Z)
                              + 2*np.sin(Y)*np.cos(Y)*np.cos(Z)*np.sin(X)
                              + 2*np.sin(Z)*np.cos(Z)*np.cos(X)*np.sin(Y))
                - 0.5 * w[1] * (np.cos(2*X)*np.cos(2*Y) + np.cos(2*Y)*np.cos(2*Z) + np.cos(2*Z)*np.cos(2*X)))
    elif t == 'splitp':
        return (1.1 * w[0] * (2*np.sin(X)*np.cos(X)*np.cos(Y)*np.sin(Z)
                              + 2*np.sin(X)*np.sin(Y)*np.cos(Y)*np.cos(Z)
                              + 2*np.cos(X)*np.sin(Y)*np.sin(Z)*np.cos(Z))
                - 0.2 * w[1] * (np.cos(2*X)*np.cos(2*Y) + np.cos(2*Y)*np.cos(2*Z) + np.cos(2*Z)*np.cos(2*X))
                - 0.4 * w[2] * (np.cos(2*X) + np.cos(2*Y) + np.cos(2*Z)))
    else:
        raise ValueError(f'Unsupported type: {t}')

V = tpms_field(X, Y, Z, weights)

# 异构混合模式
if ${state.hybrid.enabled ? 'True' : 'False'}:
    type_b = '${state.hybrid.typeB}'
    weights_b = [${hybridWeights ? hybridWeights.join(', ') : ''}]
    V_b = tpms_field(X, Y, Z, weights_b, type_b)
    blend_center = ${state.hybrid.blendCenter}
    blend_width = ${state.hybrid.blendWidth}
    t = (X / np.pi - blend_center) / blend_width
    alpha = 1 / (1 + np.exp(-5 * t))  # sigmoid
    V = V * (1 - alpha) + V_b * alpha

# 容器裁剪
if container == 'cylinder':
    r2 = X**2 + Y**2
    V[r2 > 1] = np.nan

# Marching Cubes 提取等值面
grid = pv.UniformGrid()
grid.dimensions = np.array(V.shape) + 1
grid.origin = (-1, -1, -1)
grid.spacing = (2/(N-1), 2/(N-1), 2/(N-1))
grid.cell_data['values'] = V.flatten(order='F')

# 估算等值
if structure_mode == 'gradient_shell':
    px = X / np.pi
    py = Y / np.pi
    pz = Z / np.pi
    if gradient_dir == 'z':
        scale = 1.5 - (pz + 1) * 0.5
    elif gradient_dir == 'radial':
        r2 = px**2 + py**2
        scale = np.maximum(1.5 - np.minimum(r2 / 2, 1.4), 0.1)
    elif gradient_dir == 'spherical':
        r2 = px**2 + py**2 + pz**2
        scale = np.maximum(1.5 - np.minimum(r2 / 3, 1.4), 0.1)
    else:
        scale = 1.0
    t_eff = max(0.05, thickness * 1.5)
    t_grad = t_eff * scale
    V = (V - 0)**2 - (t_grad / 2)**2
    grid.cell_data['values'] = V.flatten(order='F')
    iso = 0.0
elif structure_mode == 'shell':
    t_eff = max(0.05, thickness * 1.5)
    V = V**2 - (t_eff / 2)**2
    grid.cell_data['values'] = V.flatten(order='F')
    iso = 0.0
else:
    # solid_network：二分搜索找到使 solid fraction = 1 - porosity/100 的 iso
    target_solid = max(0.05, min(0.95, 1 - porosity/100))
    valid = ~np.isnan(V)
    v_min, v_max = np.nanmin(V), np.nanmax(V)
    for _ in range(30):
        iso = (v_min + v_max) / 2
        solid_frac = (V[valid] > iso).sum() / valid.sum()
        if solid_frac > target_solid:
            v_min = iso
        else:
            v_max = iso

mesh = grid.contour([iso])

mesh.save('tpms_reconstructed.vtk')
print(f'重建完成: {mesh.n_points} 顶点, {mesh.n_cells} 面片')
`;
  downloadBlob(new Blob([script], { type: 'text/x-python' }), filename);
}

/**
 * 导出 MATLAB 重建脚本
 */
export function exportMatlabScript(state: AppState, filename: string): void {
  const hybridWeights = state.hybrid.enabled ? getDefaultWeights(state.hybrid.typeB) : null;
  const script = `% TPMS 参数化重建脚本 (MATLAB)
% Generated by TPMS Explorer
% 注意：本平台使用 Surface Nets 算法，而脚本使用 Marching Cubes，结果可能略有差异。

tpms_type = '${state.type}';
porosity = ${state.porosity};
cell_size = ${state.cellSize};
thickness = ${state.thickness};
weights = [${state.weights.join(', ')}];
structure_mode = '${state.structureMode}';
container = '${state.containerShape}';
gradient_dir = '${state.gradientDir}';

R = 19 + cell_size * 14;
N = R + 1;
x = linspace(-pi, pi, N);
y = linspace(-pi, pi, N);
z = linspace(-pi, pi, N);
[X, Y, Z] = meshgrid(x, y, z);

% 隐函数场
if strcmp(tpms_type, 'gyroid')
    V = weights(1)*sin(X).*cos(Y) + weights(2)*sin(Y).*cos(Z) + weights(3)*sin(Z).*cos(X);
elseif strcmp(tpms_type, 'diamond')
    V = weights(1)*cos(X).*cos(Y).*cos(Z) - weights(2)*sin(X).*sin(Y).*sin(Z) ...
      + weights(3)*cos(X).*sin(Y).*sin(Z) + weights(4)*sin(X).*cos(Y).*sin(Z);
elseif strcmp(tpms_type, 'schwarz')
    V = weights(1)*cos(X) + weights(2)*cos(Y) + weights(3)*cos(Z);
elseif strcmp(tpms_type, 'neovius')
    V = 3*weights(1)*(cos(X) + cos(Y) + cos(Z)) + 4*weights(2)*cos(X).*cos(Y).*cos(Z);
elseif strcmp(tpms_type, 'iwp')
    V = 2*weights(1)*(cos(X).*cos(Y) + cos(Y).*cos(Z) + cos(Z).*cos(X)) ...
      - weights(2)*(cos(2*X) + cos(2*Y) + cos(2*Z));
elseif strcmp(tpms_type, 'frd')
    V = 4*weights(1)*cos(X).*cos(Y).*cos(Z) ...
      - weights(2)*(cos(2*X).*cos(2*Y) + cos(2*Y).*cos(2*Z) + cos(2*Z).*cos(2*X));
elseif strcmp(tpms_type, 'lidinoid')
    V = 0.5*weights(1)*(2*sin(X).*cos(X).*cos(Y).*sin(Z) ...
            + 2*sin(Y).*cos(Y).*cos(Z).*sin(X) ...
            + 2*sin(Z).*cos(Z).*cos(X).*sin(Y)) ...
        - 0.5*weights(2)*(cos(2*X).*cos(2*Y) + cos(2*Y).*cos(2*Z) + cos(2*Z).*cos(2*X));
elseif strcmp(tpms_type, 'splitp')
    V = 1.1*weights(1)*(2*sin(X).*cos(X).*cos(Y).*sin(Z) ...
            + 2*sin(X).*sin(Y).*cos(Y).*cos(Z) ...
            + 2*cos(X).*sin(Y).*sin(Z).*cos(Z)) ...
        - 0.2*weights(2)*(cos(2*X).*cos(2*Y) + cos(2*Y).*cos(2*Z) + cos(2*Z).*cos(2*X)) ...
        - 0.4*weights(3)*(cos(2*X) + cos(2*Y) + cos(2*Z));
else
    error('Unsupported TPMS type');
end

% 异构混合模式
if ${state.hybrid.enabled}
    type_b = '${state.hybrid.typeB}';
    weights_b = [${hybridWeights ? hybridWeights.join(', ') : ''}];
    if strcmp(type_b, 'gyroid')
        V_b = weights_b(1)*sin(X).*cos(Y) + weights_b(2)*sin(Y).*cos(Z) + weights_b(3)*sin(Z).*cos(X);
    elseif strcmp(type_b, 'diamond')
        V_b = weights_b(1)*cos(X).*cos(Y).*cos(Z) - weights_b(2)*sin(X).*sin(Y).*sin(Z) ...
              + weights_b(3)*cos(X).*sin(Y).*sin(Z) + weights_b(4)*sin(X).*cos(Y).*sin(Z);
    elseif strcmp(type_b, 'schwarz')
        V_b = weights_b(1)*cos(X) + weights_b(2)*cos(Y) + weights_b(3)*cos(Z);
    elseif strcmp(type_b, 'neovius')
        V_b = 3*weights_b(1)*(cos(X) + cos(Y) + cos(Z)) + 4*weights_b(2)*cos(X).*cos(Y).*cos(Z);
    elseif strcmp(type_b, 'iwp')
        V_b = 2*weights_b(1)*(cos(X).*cos(Y) + cos(Y).*cos(Z) + cos(Z).*cos(X)) ...
              - weights_b(2)*(cos(2*X) + cos(2*Y) + cos(2*Z));
    elseif strcmp(type_b, 'frd')
        V_b = 4*weights_b(1)*cos(X).*cos(Y).*cos(Z) ...
              - weights_b(2)*(cos(2*X).*cos(2*Y) + cos(2*Y).*cos(2*Z) + cos(2*Z).*cos(2*X));
    elseif strcmp(type_b, 'lidinoid')
        V_b = 0.5*weights_b(1)*(2*sin(X).*cos(X).*cos(Y).*sin(Z) ...
                + 2*sin(Y).*cos(Y).*cos(Z).*sin(X) ...
                + 2*sin(Z).*cos(Z).*cos(X).*sin(Y)) ...
              - 0.5*weights_b(2)*(cos(2*X).*cos(2*Y) + cos(2*Y).*cos(2*Z) + cos(2*Z).*cos(2*X));
    elseif strcmp(type_b, 'splitp')
        V_b = 1.1*weights_b(1)*(2*sin(X).*cos(X).*cos(Y).*sin(Z) ...
                + 2*sin(X).*sin(Y).*cos(Y).*cos(Z) ...
                + 2*cos(X).*sin(Y).*sin(Z).*cos(Z)) ...
              - 0.2*weights_b(2)*(cos(2*X).*cos(2*Y) + cos(2*Y).*cos(2*Z) + cos(2*Z).*cos(2*X)) ...
              - 0.4*weights_b(3)*(cos(2*X) + cos(2*Y) + cos(2*Z));
    else
        error('Unsupported hybrid TPMS type');
    end
    blend_center = ${state.hybrid.blendCenter};
    blend_width = ${state.hybrid.blendWidth};
    t = (X / pi - blend_center) / blend_width;
    alpha = 1 ./ (1 + exp(-5 * t));  % sigmoid
    V = V .* (1 - alpha) + V_b .* alpha;
end

% 容器裁剪
if strcmp(container, 'cylinder')
    V(X.^2 + Y.^2 > 1) = NaN;
end

% 等值面提取
if strcmp(structure_mode, 'gradient_shell')
    px = X / pi;
    py = Y / pi;
    pz = Z / pi;
    if strcmp(gradient_dir, 'z')
        scale = 1.5 - (pz + 1) * 0.5;
    elseif strcmp(gradient_dir, 'radial')
        r2 = px.^2 + py.^2;
        scale = max(1.5 - min(r2/2, 1.4), 0.1);
    elseif strcmp(gradient_dir, 'spherical')
        r2 = px.^2 + py.^2 + pz.^2;
        scale = max(1.5 - min(r2/3, 1.4), 0.1);
    else
        scale = 1.0;
    end
    t_eff = max(0.05, thickness * 1.5);
    t_grad = t_eff .* scale;
    V = (V - 0).^2 - (t_grad / 2).^2;
    iso = 0;
elseif strcmp(structure_mode, 'shell')
    t_eff = max(0.05, thickness * 1.5);
    V = V.^2 - (t_eff / 2)^2;
    iso = 0;
else
    % solid_network：二分搜索找到使 solid fraction = 1 - porosity/100 的 iso
    target_solid = max(0.05, min(0.95, 1 - porosity/100));
    valid_mask = ~isnan(V);
    valid_count = sum(valid_mask(:));
    v_min = min(V(valid_mask));
    v_max = max(V(valid_mask));
    for iter = 1:30
        iso = (v_min + v_max) / 2;
        solid_frac = sum(V(valid_mask) > iso) / valid_count;
        if solid_frac > target_solid
            v_min = iso;
        else
            v_max = iso;
        end
    end
end

figure;
p = patch(isosurface(X, Y, Z, V, iso));
isonormals(X, Y, Z, V, p);
p.FaceColor = 'red';
p.EdgeColor = 'none';
daspect([1 1 1]);
view(3);
camlight;
lighting gouraud;
`;
  downloadBlob(new Blob([script], { type: 'text/plain' }), filename);
}
