import type { AppState } from '../types';
import { downloadBlob } from './download';

/**
 * 纵深防御：插值进 Python/MATLAB 单引号字符串的标识符统一走此函数，
 * 只放行 [A-Za-z0-9_-]，其余替换为 _（防 URL 参数注入可执行代码，历史上 hybridType 曾旁路白名单）
 */
function safeId(v: string | number | boolean): string {
  return typeof v === 'string' ? v.replace(/[^A-Za-z0-9_-]/g, '_') : String(v);
}

/**
 * 导出 Python (PyVista/NumPy) 重建脚本
 *
 * 与平台实现的对齐契约（.verify/parity_math.mjs 静态断言守护，改动前先跑测试）：
 *  - 公式频率乘 kk（周期数）：平台顶点域 [-π,π]、周期编码在频率 sin(kk·x)，脚本必须同构
 *  - hybrid：alpha 陡度 6/width、V = alpha·V_A + (1-alpha)·V_B（px→+1 侧为 A）、linear 分支 clip
 *  - solid_network：solid = {V < iso}（二分分支方向与平台一致），clamp 0.02~0.98
 *  - shell / gradient_shell：t_eff 由孔隙率二分求解（lb(-t/2) + (n-lb(t/2))），thickness 仅作初值下限
 *  - 容器：F = max(F_mode, bound)，bound 为 SDF（外部 ≥0 即固相包裹），等值面取 0；不用 NaN
 *  - 网格坐标输出 mm（origin=-cellSize/2、spacing=cellSize/(N-1)，1 period=1mm）
 */
export function exportPythonScript(state: AppState, filename: string): void {
  const script = `# TPMS 参数化重建脚本 (PyVista)
# Generated by TPMS Explorer
# 本脚本与平台逐点对齐：相同参数下等值面位置一致（算法差异仅剩 MC vs Surface Nets 的网格化误差）。
# 运行: pip install numpy pyvista

import numpy as np
import pyvista as pv

# 参数配置
tpms_type = '${safeId(state.type)}'
porosity = ${state.porosity}
cell_size = ${state.cellSize}      # 周期数 k（1 period = 1 mm，模型总宽 = cell_size mm）
thickness = ${state.thickness}
weights = [${state.weights.join(', ')}]
structure_mode = '${safeId(state.structureMode)}'
container = '${safeId(state.containerShape)}'
gradient_dir = '${safeId(state.gradientDir)}'
endplate_mm = ${state.endplateMm}   # 实心加载端板单侧厚度 mm（0=关；生效值钳制至 0.4*L）

kk = cell_size  # 频率倍率：平台顶点域恒 [-pi, pi]，周期数编码在频率上
# 倍频曲面（I-WP/F-RD 含 cos2kx 项）特征频率 2k，分辨率密度加倍补偿弦切误差
fk = 28 if (tpms_type in ('iwp', 'frd', 'neovius') or (structure_mode == 'gradient_shell' and gradient_dir != 'z')) else 14
# A2 密度保优：触 96 上限后预算让渡给每周期密度（与平台 units.hdResolution 同源）
r_lin = 19 + cell_size * fk
R = int(r_lin) if r_lin <= 96 else int(min(96, np.ceil(cell_size * fk)))
N = R + 1

# 生成坐标网格（弧度域 [-pi, pi]，公式频率乘 kk）
x = np.linspace(-np.pi, np.pi, N)
y = np.linspace(-np.pi, np.pi, N)
z = np.linspace(-np.pi, np.pi, N)
X, Y, Z = np.meshgrid(x, y, z, indexing='ij')

# 隐函数场（与平台 core/tpms-functions.ts 逐项一致）
def tpms_field(X, Y, Z, w, tpms_type_override=None):
    t = tpms_type_override if tpms_type_override is not None else tpms_type
    if t == 'gyroid':
        return w[0]*np.sin(kk*X)*np.cos(kk*Y) + w[1]*np.sin(kk*Y)*np.cos(kk*Z) + w[2]*np.sin(kk*Z)*np.cos(kk*X)
    elif t == 'diamond':
        return (w[0]*np.sin(kk*X)*np.sin(kk*Y)*np.sin(kk*Z)
                + w[1]*np.sin(kk*X)*np.cos(kk*Y)*np.cos(kk*Z)
                + w[2]*np.cos(kk*X)*np.sin(kk*Y)*np.cos(kk*Z)
                + w[3]*np.cos(kk*X)*np.cos(kk*Y)*np.sin(kk*Z))
    elif t == 'schwarz':
        return w[0]*np.cos(kk*X) + w[1]*np.cos(kk*Y) + w[2]*np.cos(kk*Z)
    elif t == 'neovius':
        return 3*w[0]*(np.cos(kk*X) + np.cos(kk*Y) + np.cos(kk*Z)) + 4*w[1]*np.cos(kk*X)*np.cos(kk*Y)*np.cos(kk*Z)
    elif t == 'iwp':
        return (2*w[0]*(np.cos(kk*X)*np.cos(kk*Y) + np.cos(kk*Y)*np.cos(kk*Z) + np.cos(kk*Z)*np.cos(kk*X))
                - w[1]*(np.cos(2*kk*X) + np.cos(2*kk*Y) + np.cos(2*kk*Z)))
    elif t == 'frd':
        return (4*w[0]*np.cos(kk*X)*np.cos(kk*Y)*np.cos(kk*Z)
                - w[1]*(np.cos(2*kk*X)*np.cos(2*kk*Y) + np.cos(2*kk*Y)*np.cos(2*kk*Z) + np.cos(2*kk*Z)*np.cos(2*kk*X)))
    elif t == 'lidinoid':
        return (0.5 * w[0] * (2*np.sin(kk*X)*np.cos(kk*X)*np.cos(kk*Y)*np.sin(kk*Z)
                              + 2*np.sin(kk*Y)*np.cos(kk*Y)*np.cos(kk*Z)*np.sin(kk*X)
                              + 2*np.sin(kk*Z)*np.cos(kk*Z)*np.cos(kk*X)*np.sin(kk*Y))
                - 0.5 * w[1] * (np.cos(2*kk*X)*np.cos(2*kk*Y) + np.cos(2*kk*Y)*np.cos(2*kk*Z) + np.cos(2*kk*Z)*np.cos(2*kk*X)))
    elif t == 'splitp':
        return (1.1 * w[0] * (2*np.sin(kk*X)*np.cos(kk*X)*np.cos(kk*Y)*np.sin(kk*Z)
                              + 2*np.sin(kk*X)*np.sin(kk*Y)*np.cos(kk*Y)*np.cos(kk*Z)
                              + 2*np.cos(kk*X)*np.sin(kk*Y)*np.sin(kk*Z)*np.cos(kk*Z))
                - 0.2 * w[1] * (np.cos(2*kk*X)*np.cos(2*kk*Y) + np.cos(2*kk*Y)*np.cos(2*kk*Z) + np.cos(2*kk*Z)*np.cos(2*kk*X))
                - 0.4 * w[2] * (np.cos(2*kk*X) + np.cos(2*kk*Y) + np.cos(2*kk*Z)))
    else:
        raise ValueError(f'Unsupported type: {t}')

V = tpms_field(X, Y, Z, weights)

# 异构混合模式（与 core/hybrid-functions.ts 对齐：px→+1 侧为 A 主导）
blend_function = '${safeId(state.hybrid.blendFunction)}'
if ${state.hybrid.enabled ? 'True' : 'False'}:
    type_b = '${safeId(state.hybrid.typeB)}'
    weights_b = [${state.weights.join(', ')}]  # 与平台同源（平台 B 场复用主权重，非默认权重）
    V_b = tpms_field(X, Y, Z, weights_b, type_b)
    blend_center = ${safeId(state.hybrid.blendCenter)}
    blend_width = ${safeId(state.hybrid.blendWidth)}
    t_px = X / np.pi  # 物理坐标 [-1, 1]
    if blend_function == 'linear':
        half_w = blend_width / 2
        alpha = np.clip((t_px - (blend_center - half_w)) / blend_width, 0.0, 1.0)
    else:  # sigmoid
        k_sig = 6.0 / max(blend_width, 0.01)
        alpha = 1 / (1 + np.exp(-k_sig * (t_px - blend_center)))
    V = alpha * V + (1 - alpha) * V_b

# 容器边界场（SDF：外部 >= 0 = 固相包裹，与平台 max(f, bound) 一致；不用 NaN）
px = X / np.pi
py = Y / np.pi
pz = Z / np.pi
if container == 'cylinder':
    bound = np.maximum(px**2 + py**2 - 1, np.abs(pz) - 1)
else:
    bound = np.maximum(np.maximum(np.abs(px) - 1, np.abs(py) - 1), np.abs(pz) - 1)

# 模式场与孔隙率二分（与平台 surface-nets.ts 同一算法：容器内网格角点分位数）
inside = bound < 0
target_solid = max(0.02, min(0.98, 1 - porosity/100))
v_in = np.sort(V[inside])
n_in = v_in.size

if structure_mode == 'gradient_shell':
    # 二分解 t_eff（无梯度对称壳计数），再乘梯度 scale —— 与平台一致
    def count_shell(t):
        return np.searchsorted(v_in, -t/2, side='left') + (n_in - np.searchsorted(v_in, t/2, side='left'))
    lo, hi = 0.02, (v_in[-1] - v_in[0]) * 4
    for _ in range(18):
        t_eff = (lo + hi) / 2
        if count_shell(t_eff) / n_in > target_solid: lo = t_eff
        else: hi = t_eff
    t_eff = (lo + hi) / 2  # 平台无 0.05 下限，保持一致
    if gradient_dir == 'z':
        scale = 1.5 - (pz + 1) * 0.5
    elif gradient_dir == 'radial':
        scale = np.maximum(1.5 - np.minimum((px**2 + py**2) / 2, 1.4), 0.1)
    elif gradient_dir == 'spherical':
        scale = np.maximum(1.5 - np.minimum((px**2 + py**2 + pz**2) / 3, 1.4), 0.1)
    else:
        scale = 1.0
    F = (V - 0)**2 - (t_eff * scale / 2)**2
elif structure_mode == 'shell':
    def count_shell(t):
        return np.searchsorted(v_in, -t/2, side='left') + (n_in - np.searchsorted(v_in, t/2, side='left'))
    lo, hi = 0.02, (v_in[-1] - v_in[0]) * 4
    for _ in range(18):
        t_eff = (lo + hi) / 2
        if count_shell(t_eff) / n_in > target_solid: lo = t_eff
        else: hi = t_eff
    t_eff = (lo + hi) / 2  # 平台无 0.05 下限，保持一致
    F = V**2 - (t_eff / 2)**2
else:
    # solid_network：solid = {V < iso}（与平台一致），16 轮二分收敛到下分位数
    lo, hi = v_in[0] - 0.5, v_in[-1] + 0.5
    for _ in range(16):
        iso_bias = (lo + hi) / 2
        solid_frac = (V[inside] < iso_bias).sum() / n_in
        if solid_frac > target_solid: hi = iso_bias
        else: lo = iso_bias
    iso_bias = (lo + hi) / 2
    F = iso_bias - V

# 【2026-08-27 v2】统一封盖规则（与平台 surface-nets v2 一致）：
# 容器外(bound>=0)或网格边界层一律空气——max(F, bound) 不行：公式在圆柱角落的
# 正瓣会压过负裁剪（实测 +109%→+27% 教训），容器裁剪必须无条件覆写。
# 覆写后实体相在表面自然截断，孔口为开放边界；需要封闭实体时补面或布尔。
on_face = ((X == X.min()) | (X == X.max()) | (Y == Y.min()) | (Y == Y.max()) | (Z == Z.min()) | (Z == Z.max()))
F = np.where((bound >= 0) | on_face, -1e-6, np.maximum(F, bound))

# 【实心加载端板】(与平台 surface-nets endplateMm 同源)：z 带内侧向界内强制实体；
# z 向最外层豁免保持收口，x/y 出侧壁不生效
if endplate_mm > 0:
    t_pl = min(endplate_mm, 0.4 * cell_size)
    z_band = np.abs(pz) >= (1 - 2 * t_pl / cell_size)
    z_face = (Z == Z.min()) | (Z == Z.max())
    if container == 'cylinder':
        side_in = (px**2 + py**2 - 1) < 0
    else:
        side_in = np.maximum(np.abs(px) - 1, np.abs(py) - 1) < 0
    F = np.where(z_band & side_in & ~z_face, 1.0, F)

# Marching Cubes 提取等值面（F = 0；坐标为 mm，1 period = 1 mm）
# pyvista >= 0.44：UniformGrid 已改名 ImageData（旧名 0.48 起移除）；场是网格点值 → point_data
# （旧写法 cell_data + dimensions=N+1 依赖已移除的自动转换，且引入半格偏移）
grid = pv.ImageData(dimensions=V.shape, origin=(-cell_size/2, -cell_size/2, -cell_size/2), spacing=(cell_size/(N-1),)*3)
grid.point_data['values'] = F.flatten(order='F')
iso = 0.0

mesh = grid.contour([iso])

mesh.save('tpms_reconstructed.vtk')
print(f'重建完成: {mesh.n_points} 顶点, {mesh.n_cells} 面片; iso_bias={iso_bias if structure_mode == "solid_network" else 0:.6f}, t_eff={t_eff if structure_mode != "solid_network" else 0:.6f}')
`;
  downloadBlob(new Blob([script], { type: 'text/x-python' }), filename);
}

/**
 * 导出 MATLAB 重建脚本（对齐契约同 Python 版）
 */
export function exportMatlabScript(state: AppState, filename: string): void {
  const script = `% TPMS 参数化重建脚本 (MATLAB)
% Generated by TPMS Explorer
% 本脚本与平台逐点对齐：相同参数下等值面位置一致（算法差异仅剩 MC vs Surface Nets 的网格化误差）。

tpms_type = '${safeId(state.type)}';
porosity = ${state.porosity};
cell_size = ${state.cellSize};      % 周期数 k（1 period = 1 mm，模型总宽 = cell_size mm）
thickness = ${state.thickness};
weights = [${state.weights.join(', ')}];
structure_mode = '${safeId(state.structureMode)}';
container = '${safeId(state.containerShape)}';
gradient_dir = '${safeId(state.gradientDir)}';
endplate_mm = ${state.endplateMm};   % 实心加载端板单侧厚度 mm（0=关；生效值钳制至 0.4*L）

kk = cell_size;  % 频率倍率：平台顶点域恒 [-pi, pi]，周期数编码在频率上
% 倍频曲面（I-WP/F-RD 含 cos2kx 项）特征频率 2k，分辨率密度加倍补偿弦切误差
if any(strcmp(tpms_type, {'iwp', 'frd', 'neovius'})) || strcmp(structure_mode, 'gradient_shell') && ~strcmp(gradient_dir, 'z')
    fk = 28;
else
    fk = 14;
end
% A2 密度保优：触 96 上限后预算让渡给每周期密度（与平台 units.hdResolution 同源）
r_lin = 19 + cell_size * fk;
if r_lin <= 96
    R = round(r_lin);
else
    R = min(96, ceil(cell_size * fk));
end
N = R + 1;
x = linspace(-pi, pi, N);
y = linspace(-pi, pi, N);
z = linspace(-pi, pi, N);
[X, Y, Z] = meshgrid(x, y, z);

% 隐函数场（与平台 core/tpms-functions.ts 逐项一致）
if strcmp(tpms_type, 'gyroid')
    V = weights(1)*sin(kk*X).*cos(kk*Y) + weights(2)*sin(kk*Y).*cos(kk*Z) + weights(3)*sin(kk*Z).*cos(kk*X);
elseif strcmp(tpms_type, 'diamond')
    V = weights(1)*sin(kk*X).*sin(kk*Y).*sin(kk*Z) ...
      + weights(2)*sin(kk*X).*cos(kk*Y).*cos(kk*Z) ...
      + weights(3)*cos(kk*X).*sin(kk*Y).*cos(kk*Z) ...
      + weights(4)*cos(kk*X).*cos(kk*Y).*sin(kk*Z);
elseif strcmp(tpms_type, 'schwarz')
    V = weights(1)*cos(kk*X) + weights(2)*cos(kk*Y) + weights(3)*cos(kk*Z);
elseif strcmp(tpms_type, 'neovius')
    V = 3*weights(1)*(cos(kk*X) + cos(kk*Y) + cos(kk*Z)) + 4*weights(2)*cos(kk*X).*cos(kk*Y).*cos(kk*Z);
elseif strcmp(tpms_type, 'iwp')
    V = 2*weights(1)*(cos(kk*X).*cos(kk*Y) + cos(kk*Y).*cos(kk*Z) + cos(kk*Z).*cos(kk*X)) ...
      - weights(2)*(cos(2*kk*X) + cos(2*kk*Y) + cos(2*kk*Z));
elseif strcmp(tpms_type, 'frd')
    V = 4*weights(1)*cos(kk*X).*cos(kk*Y).*cos(kk*Z) ...
      - weights(2)*(cos(2*kk*X).*cos(2*kk*Y) + cos(2*kk*Y).*cos(2*kk*Z) + cos(2*kk*Z).*cos(2*kk*X));
elseif strcmp(tpms_type, 'lidinoid')
    V = 0.5*weights(1)*(2*sin(kk*X).*cos(kk*X).*cos(kk*Y).*sin(kk*Z) ...
            + 2*sin(kk*Y).*cos(kk*Y).*cos(kk*Z).*sin(kk*X) ...
            + 2*sin(kk*Z).*cos(kk*Z).*cos(kk*X).*sin(kk*Y)) ...
        - 0.5*weights(2)*(cos(2*kk*X).*cos(2*kk*Y) + cos(2*kk*Y).*cos(2*kk*Z) + cos(2*kk*Z).*cos(2*kk*X));
elseif strcmp(tpms_type, 'splitp')
    V = 1.1*weights(1)*(2*sin(kk*X).*cos(kk*X).*cos(kk*Y).*sin(kk*Z) ...
            + 2*sin(kk*X).*sin(kk*Y).*cos(kk*Y).*cos(kk*Z) ...
            + 2*cos(kk*X).*sin(kk*Y).*sin(kk*Z).*cos(kk*Z)) ...
        - 0.2*weights(2)*(cos(2*kk*X).*cos(2*kk*Y) + cos(2*kk*Y).*cos(2*kk*Z) + cos(2*kk*Z).*cos(2*kk*X)) ...
        - 0.4*weights(3)*(cos(2*kk*X) + cos(2*kk*Y) + cos(2*kk*Z));
else
    error('Unsupported TPMS type');
end

% 异构混合模式（与 core/hybrid-functions.ts 对齐：px→+1 侧为 A 主导）
blend_function = '${safeId(state.hybrid.blendFunction)}';
if ${safeId(state.hybrid.enabled)}
    type_b = '${safeId(state.hybrid.typeB)}';
    weights_b = [${state.weights.join(', ')}]  # 与平台同源（平台 B 场复用主权重，非默认权重）;
    if strcmp(type_b, 'gyroid')
        V_b = weights_b(1)*sin(kk*X).*cos(kk*Y) + weights_b(2)*sin(kk*Y).*cos(kk*Z) + weights_b(3)*sin(kk*Z).*cos(kk*X);
    elseif strcmp(type_b, 'diamond')
        V_b = weights_b(1)*sin(kk*X).*sin(kk*Y).*sin(kk*Z) ...
              + weights_b(2)*sin(kk*X).*cos(kk*Y).*cos(kk*Z) ...
              + weights_b(3)*cos(kk*X).*sin(kk*Y).*cos(kk*Z) ...
              + weights_b(4)*cos(kk*X).*cos(kk*Y).*sin(kk*Z);
    elseif strcmp(type_b, 'schwarz')
        V_b = weights_b(1)*cos(kk*X) + weights_b(2)*cos(kk*Y) + weights_b(3)*cos(kk*Z);
    elseif strcmp(type_b, 'neovius')
        V_b = 3*weights_b(1)*(cos(kk*X) + cos(kk*Y) + cos(kk*Z)) + 4*weights_b(2)*cos(kk*X).*cos(kk*Y).*cos(kk*Z);
    elseif strcmp(type_b, 'iwp')
        V_b = 2*weights_b(1)*(cos(kk*X).*cos(kk*Y) + cos(kk*Y).*cos(kk*Z) + cos(kk*Z).*cos(kk*X)) ...
              - weights_b(2)*(cos(2*kk*X) + cos(2*kk*Y) + cos(2*kk*Z));
    elseif strcmp(type_b, 'frd')
        V_b = 4*weights_b(1)*cos(kk*X).*cos(kk*Y).*cos(kk*Z) ...
              - weights_b(2)*(cos(2*kk*X).*cos(2*kk*Y) + cos(2*kk*Y).*cos(2*kk*Z) + cos(2*kk*Z).*cos(2*kk*X));
    elseif strcmp(type_b, 'lidinoid')
        V_b = 0.5*weights_b(1)*(2*sin(kk*X).*cos(kk*X).*cos(kk*Y).*sin(kk*Z) ...
                + 2*sin(kk*Y).*cos(kk*Y).*cos(kk*Z).*sin(kk*X) ...
                + 2*sin(kk*Z).*cos(kk*Z).*cos(kk*X).*sin(kk*Y)) ...
              - 0.5*weights_b(2)*(cos(2*kk*X).*cos(2*kk*Y) + cos(2*kk*Y).*cos(2*kk*Z) + cos(2*kk*Z).*cos(2*kk*X));
    elseif strcmp(type_b, 'splitp')
        V_b = 1.1*weights_b(1)*(2*sin(kk*X).*cos(kk*X).*cos(kk*Y).*sin(kk*Z) ...
                + 2*sin(kk*X).*sin(kk*Y).*cos(kk*Y).*cos(kk*Z) ...
                + 2*cos(kk*X).*sin(kk*Y).*sin(kk*Z).*cos(kk*Z)) ...
              - 0.2*weights_b(2)*(cos(2*kk*X).*cos(2*kk*Y) + cos(2*kk*Y).*cos(2*kk*Z) + cos(2*kk*Z).*cos(2*kk*X)) ...
              - 0.4*weights_b(3)*(cos(2*kk*X) + cos(2*kk*Y) + cos(2*kk*Z));
    else
        error('Unsupported hybrid TPMS type');
    end
    blend_center = ${safeId(state.hybrid.blendCenter)};
    blend_width = ${safeId(state.hybrid.blendWidth)};
    t_px = X / pi;  % 物理坐标 [-1, 1]
    if strcmp(blend_function, 'linear')
        half_w = blend_width / 2;
        alpha = min(max((t_px - (blend_center - half_w)) / blend_width, 0), 1);
    else  % sigmoid
        k_sig = 6.0 / max(blend_width, 0.01);
        alpha = 1 ./ (1 + exp(-k_sig * (t_px - blend_center)));
    end
    V = alpha .* V + (1 - alpha) .* V_b;
end

% 容器边界场（SDF：外部 >= 0 = 固相包裹，与平台 max(f, bound) 一致；不用 NaN）
px = X / pi;
py = Y / pi;
pz = Z / pi;
if strcmp(container, 'cylinder')
    bound = max(px.^2 + py.^2 - 1, abs(pz) - 1);
else
    bound = max(max(abs(px) - 1, abs(py) - 1), abs(pz) - 1);
end

% 模式场与孔隙率二分（与平台 surface-nets.ts 同一算法：容器内网格角点分位数）
inside = bound < 0;
target_solid = max(0.02, min(0.98, 1 - porosity/100));
v_in = sort(V(inside));
n_in = numel(v_in);

if strcmp(structure_mode, 'gradient_shell')
    lo = 0.02; hi = (v_in(end) - v_in(1)) * 4;
    for iter = 1:18
        t_eff = (lo + hi) / 2;
        cnt = sum(v_in < -t_eff/2) + (n_in - sum(v_in < t_eff/2));
        if cnt / n_in > target_solid, lo = t_eff; else, hi = t_eff; end
    end
    t_eff = (lo + hi) / 2;  % 平台无 0.05 下限，保持一致
    if strcmp(gradient_dir, 'z')
        scale = 1.5 - (pz + 1) * 0.5;
    elseif strcmp(gradient_dir, 'radial')
        scale = max(1.5 - min((px.^2 + py.^2) / 2, 1.4), 0.1);
    elseif strcmp(gradient_dir, 'spherical')
        scale = max(1.5 - min((px.^2 + py.^2 + pz.^2) / 3, 1.4), 0.1);
    else
        scale = 1.0;
    end
    F = (V - 0).^2 - (t_eff .* scale / 2).^2;
elseif strcmp(structure_mode, 'shell')
    lo = 0.02; hi = (v_in(end) - v_in(1)) * 4;
    for iter = 1:18
        t_eff = (lo + hi) / 2;
        cnt = sum(v_in < -t_eff/2) + (n_in - sum(v_in < t_eff/2));
        if cnt / n_in > target_solid, lo = t_eff; else, hi = t_eff; end
    end
    t_eff = (lo + hi) / 2;  % 平台无 0.05 下限，保持一致
    F = V.^2 - (t_eff / 2)^2;
else
    % solid_network：solid = {V < iso}（与平台一致），16 轮二分收敛到下分位数
    lo = v_in(1) - 0.5; hi = v_in(end) + 0.5;
    for iter = 1:16
        iso_bias = (lo + hi) / 2;
        solid_frac = sum(v_in < iso_bias) / n_in;
        if solid_frac > target_solid, hi = iso_bias; else, lo = iso_bias; end
    end
    iso_bias = (lo + hi) / 2;
    F = iso_bias - V;
end

F = max(F, bound);
% 【2026-08-27 v2】统一封盖规则（与平台 surface-nets v2 一致）：
% 容器外(bound>=0)或网格边界层一律空气——max 裁剪会被公式正瓣压过（实测教训）。
on_face = (X == min(X(:))) | (X == max(X(:))) | (Y == min(Y(:))) | (Y == max(Y(:))) | (Z == min(Z(:))) | (Z == max(Z(:)));
F(bound >= 0 | on_face) = -1e-6;

% 【实心加载端板】(与平台 surface-nets endplateMm 同源)
if endplate_mm > 0
    t_pl = min(endplate_mm, 0.4 * cell_size);
    z_band = abs(pz) >= (1 - 2 * t_pl / cell_size);
    z_face = (Z == min(Z(:))) | (Z == max(Z(:)));
    if strcmp(container, 'cylinder')
        side_in = (px.^2 + py.^2 - 1) < 0;
    else
        side_in = max(abs(px) - 1, abs(py) - 1) < 0;
    end
    F(z_band & side_in & ~z_face) = 1.0;
end
iso = 0;

% mm 坐标（1 period = 1 mm）
Xm = (px / 2) * cell_size;
Ym = (py / 2) * cell_size;
Zm = (pz / 2) * cell_size;

figure;
p = patch(isosurface(Xm, Ym, Zm, F, iso));
isonormals(Xm, Ym, Zm, F, p);
p.FaceColor = 'red';
p.EdgeColor = 'none';
daspect([1 1 1]);
view(3);
camlight;
lighting gouraud;
`;
  downloadBlob(new Blob([script], { type: 'text/plain' }), filename);
}
